# Kong API Gateway Configuration for Model Serving

_format_version: "3.0"

services:
  - name: intent-classifier
    url: http://torchserve.model-serving.svc.cluster.local:8080/predictions/intent_classifier
    protocol: http
    port: 8080
    path: /predictions/intent_classifier
    retries: 3
    connect_timeout: 5000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - model-serving
      - ml
    
    routes:
      - name: intent-classifier-route
        protocols:
          - https
        hosts:
          - models.betterprompts.com
        paths:
          - /v1/models/intent-classifier/predict
        strip_path: true
        preserve_host: true
        
    plugins:
      - name: rate-limiting
        config:
          minute: 3000
          hour: 100000
          policy: local
          fault_tolerant: true
          hide_client_headers: false
          
      - name: request-size-limiting
        config:
          allowed_payload_size: 50
          size_unit: megabytes
          
      - name: response-transformer
        config:
          add:
            headers:
              X-Model-Version: "1.0"
              X-Served-By: "TorchServe"
              
      - name: correlation-id
        config:
          header_name: X-Request-ID
          generator: uuid
          echo_downstream: true
          
      - name: prometheus
        config:
          per_consumer: false
          
      - name: request-validator
        config:
          body_schema: |
            {
              "type": "object",
              "required": ["text"],
              "properties": {
                "text": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 5000
                },
                "options": {
                  "type": "object",
                  "properties": {
                    "include_alternatives": {"type": "boolean"},
                    "confidence_threshold": {"type": "number", "minimum": 0, "maximum": 1}
                  }
                }
              }
            }

  - name: model-management
    url: http://torchserve.model-serving.svc.cluster.local:8081
    protocol: http
    port: 8081
    tags:
      - model-serving
      - management
    
    routes:
      - name: model-management-route
        protocols:
          - https
        hosts:
          - models-mgmt.betterprompts.com
        paths:
          - /management
        
    plugins:
      - name: ip-restriction
        config:
          allow:
            - 10.0.0.0/8
            - 172.16.0.0/12
          status: 403
          message: "Access restricted to internal networks"
          
      - name: basic-auth
        config:
          hide_credentials: true

upstreams:
  - name: torchserve-inference
    algorithm: least-connections
    slots: 10000
    
    healthchecks:
      active:
        healthy:
          interval: 5
          successes: 2
          http_statuses:
            - 200
        unhealthy:
          interval: 5
          tcp_failures: 3
          timeouts: 3
          http_failures: 3
          http_statuses:
            - 429
            - 500
            - 503
        http_path: /ping
        timeout: 2
        type: http
        
      passive:
        healthy:
          successes: 5
          http_statuses:
            - 200
            - 201
            - 202
        unhealthy:
          tcp_failures: 2
          timeouts: 5
          http_failures: 5
          http_statuses:
            - 429
            - 500
            - 503
        type: http
    
    targets:
      - target: torchserve-0.torchserve-headless.model-serving.svc.cluster.local:8080
        weight: 100
      - target: torchserve-1.torchserve-headless.model-serving.svc.cluster.local:8080
        weight: 100
      - target: torchserve-2.torchserve-headless.model-serving.svc.cluster.local:8080
        weight: 100

plugins:
  - name: prometheus
    
  - name: zipkin
    config:
      http_endpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
      sample_ratio: 0.01
      include_credential: false
      
  - name: syslog
    config:
      successful_severity: info
      client_errors_severity: warning
      server_errors_severity: err
      
  - name: response-ratelimiting
    config:
      limits:
        inference_limit:
          minute: 100
      policy: local
      fault_tolerant: true
      
  - name: cors
    config:
      origins:
        - https://app.betterprompts.com
        - https://www.betterprompts.com
      methods:
        - GET
        - POST
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-Type
        - Authorization
        - X-Requested-With
      exposed_headers:
        - X-Request-ID
        - X-RateLimit-Limit
        - X-RateLimit-Remaining
      credentials: true
      max_age: 3600