apiVersion: v1
kind: ConfigMap
metadata:
  name: torchserve-config
  namespace: model-serving
data:
  config.properties: |
    inference_address=http://0.0.0.0:8080
    management_address=http://0.0.0.0:8081
    metrics_address=http://0.0.0.0:8082
    number_of_netty_threads=32
    job_queue_size=1000
    model_store=/models
    load_models=all
    models={\
      "intent_classifier": {\
        "1.0": {\
            "defaultVersion": true,\
            "marName": "intent_classifier.mar",\
            "minWorkers": 2,\
            "maxWorkers": 4,\
            "batchSize": 8,\
            "maxBatchDelay": 100,\
            "responseTimeout": 60\
        }\
      }\
    }
    batch_size=8
    max_batch_delay=100
    default_workers_per_model=4
    default_response_timeout=60
    cors_allowed_origin=*
    cors_allowed_methods=GET, POST, PUT, OPTIONS
    cors_allowed_headers=X-Custom-Header, Content-Type, Authorization
    enable_metrics_api=true
    metrics_format=prometheus
    enable_dynamic_batching=true
    preload_model=true
    use_native_io=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: torchserve-log4j
  namespace: model-serving
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN" monitorInterval="30">
        <Properties>
            <Property name="log-path">/var/log/torchserve</Property>
            <Property name="pattern">%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n%throwable</Property>
        </Properties>
        
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="${pattern}"/>
            </Console>
            
            <RollingFile name="RollingFile" fileName="${log-path}/torchserve.log"
                         filePattern="${log-path}/torchserve-%d{yyyy-MM-dd}-%i.log.gz">
                <PatternLayout pattern="${pattern}"/>
                <Policies>
                    <TimeBasedTriggeringPolicy interval="1" modulate="true"/>
                    <SizeBasedTriggeringPolicy size="100MB"/>
                </Policies>
                <DefaultRolloverStrategy max="30"/>
            </RollingFile>
        </Appenders>
        
        <Loggers>
            <Logger name="com.amazonaws.ml.ts" level="INFO" additivity="false">
                <AppenderRef ref="RollingFile"/>
                <AppenderRef ref="Console"/>
            </Logger>
            
            <Root level="INFO">
                <AppenderRef ref="RollingFile"/>
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>