apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: model-serving

resources:
  - namespace.yaml
  - configmap.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  project: betterprompts
  component: model-serving
  managed-by: kustomize

images:
  - name: betterprompts/torchserve
    newTag: latest