apiVersion: v1
kind: ServiceAccount
metadata:
  name: torchserve
  namespace: model-serving
  labels:
    app: torchserve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: torchserve
  namespace: model-serving
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: torchserve
  namespace: model-serving
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: torchserve
subjects:
- kind: ServiceAccount
  name: torchserve
  namespace: model-serving