# Traefik Middleware Configuration

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: model-serving
spec:
  rateLimit:
    average: 100
    burst: 50
    period: 1s
    sourceCriterion:
      ipStrategy:
        depth: 1
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: circuit-breaker
  namespace: model-serving
spec:
  circuitBreaker:
    expression: ResponseCodeRatio(500, 600, 0, 600) > 0.30 || NetworkErrorRatio() > 0.10
    checkPeriod: 10s
    fallbackDuration: 10s
    recoveryDuration: 10s
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: retry
  namespace: model-serving
spec:
  retry:
    attempts: 3
    initialInterval: 100ms
    maxInterval: 1s
    multiplier: 2
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: model-serving
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-XSS-Protection: 1; mode=block
      Referrer-Policy: no-referrer-when-downgrade
      Strict-Transport-Security: max-age=31536000; includeSubDomains
    removeResponseHeaders:
      - Server
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: model-serving
spec:
  compress:
    minResponseBodyBytes: 1024
    excludedContentTypes:
      - image/jpeg
      - image/png
      - image/gif
      - video/mp4
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: inference-chain
  namespace: model-serving
spec:
  chain:
    middlewares:
      - name: rate-limit
      - name: headers
      - name: compress
      - name: circuit-breaker
      - name: retry