apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: torchserve
spec:
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: External
    external:
      metric:
        name: datadogmetric@betterprompts:torchserve_inference_latency_p95
        selector:
          matchLabels:
            service: torchserve
      target:
        type: Value
        value: "200"  # 200ms p95 latency target