apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: model-serving

bases:
  - ../../base

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: torchserve-config
    behavior: merge
    literals:
      - default_workers_per_model=8
      - batch_size=16
      - max_batch_delay=50
      - number_of_netty_threads=64

images:
  - name: betterprompts/torchserve
    newTag: v1.0.0  # Pin to specific version

secretGenerator:
  - name: model-credentials
    literals:
      - aws_access_key_id=${AWS_ACCESS_KEY_ID}
      - aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}