apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchserve
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: torchserve
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: "0"  # No GPU in dev
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: "0"
        env:
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms1g -XX:+UseG1GC"
        - name: LOG_LEVEL
          value: "DEBUG"
      nodeSelector:
        node.kubernetes.io/gpu: null  # Remove GPU requirement