apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: model-serving-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: torchserve-config
    behavior: merge
    literals:
      - default_workers_per_model=2
      - batch_size=4

replicas:
  - name: torchserve
    count: 1